Fitness Applicatie/Controllers/ExerciseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using FitTracker.Logic;
using FitTracker.Interface.DTOs;
using Microsoft.AspNetCore.Mvc;

namespace Fitness_Applicatie.Controllers
{
    public class ExerciseController : Controller
    {
        [Authorize]
        public IActionResult AddStrengthExercise()
        {
            return View();
        }

        public ActionResult AddExerciseToDb(Models.ExerciseViewModel exercise)
        {
            return LocalRedirect("/Home/Index");
        }

        [HttpPost]
        public IActionResult AddStrengthExercise(Models.ExerciseViewModel exerciseViewModel)
        {
            try
            {
                User user = new User();
                Exercise exercise = new Exercise();
                ExerciseDTO exerciseDTO = new ExerciseDTO(exerciseViewModel.Name, Guid.Parse(User.FindFirst("Id").Value), (ExerciseTypeDTO)exerciseViewModel.ExerciseType);
                if (String.IsNullOrEmpty(exerciseViewModel.Name) || exerciseViewModel.ExerciseType.ToString() == "Empty")
                {
                    ModelState.AddModelError("Name", "Fill in all fields please");
                    return View(exerciseViewModel);
                }
                if (exercise.ExerciseExists(exerciseViewModel.Name))
                {
                    ModelState.AddModelError("Name", "Exercise already exists");
                    return View(exerciseViewModel);
                }
                else
                {
                    user.AddExercise(exerciseDTO);
                    TempData["JustAddedExercise"] = true;
                }
                return LocalRedirect("/Home/Index");
            }
            catch
            {
                TempData["Error"] = true;
                return LocalRedirect("/Home/Index");
            }
        }
    }
}

Fitness Applicatie/Controllers/TrainingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Fitness_Applicatie.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using FitTracker.Logic;
using FitTracker.Interface.DTOs;
using FitTracker.LogicInterface;
using LogicFactory;
using FitTracker.LogicFactory;

namespace Fitness_Applicatie.Controllers
{
    public class TrainingController : Controller
    {
        [Authorize]
        public IActionResult AddStrengthTraining()
        {
            return View();
        }

        [Authorize]
        public IActionResult AddCardioTraining()
        {
            return View();
        }

        [Authorize]
        public IActionResult TrainingDetail(Guid id)
        {
            try
            {
                User user = new User();
                TrainingViewModel trainingVM = ConvertTrainingDTO(user.GetTraining(id.ToString()));

                if (trainingVM.TrainingType == TrainingType.Strength)
                {
                    WeightTrainingDTO weightTrainingDTO = user.GetWeightTraining(id.ToString());
                    List<RoundViewModel> roundViewModels = new List<RoundViewModel>();
                    foreach (var roundDTO in weightTrainingDTO.GetRounds())
                    {
                        roundViewModels.Add(ConvertRoundDTO(roundDTO));
                    }
                    trainingVM.Rounds = roundViewModels;
                }

                else
                {
                    CardioTrainingDTO cardioTrainingDTO = user.GetCardioTraining(id.ToString());
                    trainingVM.Exercise = ConvertExerciseDTOToVM(cardioTrainingDTO.Exercise);
                    trainingVM.Distance = Math.Round(cardioTrainingDTO.Distance, 2);
                    trainingVM.Minutes = cardioTrainingDTO.Time.Minutes;
                    trainingVM.Seconds = cardioTrainingDTO.Time.Seconds;
                    trainingVM.TrainingID = cardioTrainingDTO.TrainingID;
                }
                return View(trainingVM);
            }

            catch
            {
                TempData["Error"] = true;
                return LocalRedirect("/Home/Index");
            }
            
        }

        [HttpPost]
        public IActionResult AddStrengthTraining(TrainingViewModel trainingViewModel)
        {
            try
            {
                foreach (var round in trainingViewModel.Rounds)
                {
                    if (String.IsNullOrEmpty(round.Exercise.Name))
                    {
                        ModelState.AddModelError("Rounds", "Fill in the exercise names");
                        return View(trainingViewModel);
                    }
                    foreach (var set in round.Sets)
                    {
                        if (set.Weight == 0)
                        {
                            ModelState.AddModelError("Rounds", "Please fill in all the weights");
                            return View(trainingViewModel);
                        }
                    }
                }
                List<RoundDTO> rounds = new List<RoundDTO>();
                foreach (var roundViewModel in trainingViewModel.Rounds)
                {
                    rounds.Add(ConvertRoundVM(roundViewModel));
                }

                WeightTrainingDTO weightTraining = new WeightTrainingDTO(rounds, Guid.Parse(User.FindFirst("Id").Value), new DateTime(2021, 1, 15), TrainingTypeDTO.Strength);
                UserCollection userCollection = new UserCollection();
                User user = ConvertUserDTO(userCollection.GetUser(User.Identity.Name));
                user.AddStrengthTraining(weightTraining);
                TempData["JustAddedTraining"] = true;
                return LocalRedirect("/Home/Index");
            }

            catch
            {
                TempData["Error"] = true;
                return LocalRedirect("/Training/AddStrengthTraining");
            }
            
        }

        [HttpPost]
        public IActionResult AddCardioTraining(TrainingViewModel trainingViewModel)
        {
            try
            {
                if (String.IsNullOrEmpty(trainingViewModel.Exercise.Name))
                {
                    ModelState.AddModelError("Exercise", "Please fill in an exercise");
                    return View(trainingViewModel);
                }

                IUser user = UserFactory.GetUser();
                IUserCollection userCollection = UserCollectionFactory.GetUserCollection();
                ExerciseDTO exerciseDTO = userCollection.GetExercise(trainingViewModel.Exercise.Name);
                CardioTrainingDTO cardioTrainingDTO = new CardioTrainingDTO(exerciseDTO, trainingViewModel.Distance, new TimeSpan(0, trainingViewModel.Minutes, trainingViewModel.Seconds), Guid.Parse(User.FindFirst("Id").Value), DateTime.Now, TrainingTypeDTO.Cardio);
                user.AddCardioTraining(cardioTrainingDTO);
                TempData["JustAddedTraining"] = true;
                return LocalRedirect("/Home/Index");
            }

            catch
            {
                TempData["Error"] = true;
                return LocalRedirect("/Training/AddCardioTraining");
            }
        }

        [HttpPost]
        public IActionResult DeleteTraining(TrainingViewModel trainingViewModel)
        {
            User user = new User();
            if (trainingViewModel.TrainingType == TrainingType.Strength)
            {
                user.DeleteWeightTraining(trainingViewModel.TrainingID.ToString());
            }

            else
            {
                user.DeleteCardioTraining(trainingViewModel.TrainingID.ToString());
            }
            return LocalRedirect("/Home/Index");
        }

        private RoundDTO ConvertRoundVM(RoundViewModel roundViewModel)
        {
            List<SetDTO> sets = new List<SetDTO>();
            foreach (var set in roundViewModel.Sets)
            {
                set.SetOrder = roundViewModel.Sets.IndexOf(set);
                sets.Add(ConvertSetVM(set));
            }
            UserCollection userCollection = new UserCollection();
            ExerciseDTO exercise = userCollection.GetExercise(roundViewModel.Exercise.Name);
            RoundDTO round = new RoundDTO(exercise, exercise.ExerciseID, sets);
            return round;
        }

        private RoundViewModel ConvertRoundDTO(RoundDTO roundDTO)
        {
            List<SetViewModel> setViewModels = new List<SetViewModel>();
            foreach (var setDTO in roundDTO.GetSets())
            {
                setViewModels.Add(ConvertSetDTO(setDTO));
            };
            RoundViewModel roundViewModel = new RoundViewModel
            {
                Exercise = ConvertExerciseDTOToVM(roundDTO.Exercise),
                ExerciseID = roundDTO.ExerciseID,
                RoundID = roundDTO.RoundID,
                TrainingID = roundDTO.TrainingID,
                Sets = setViewModels
            };
            return roundViewModel;
        }

        private SetDTO ConvertSetVM(SetViewModel setViewModel)
        {
            SetDTO set = new SetDTO(setViewModel.Weight, setViewModel.SetOrder);
            return set;
        }

        private Exercise ConvertExerciseDTO(ExerciseDTO exerciseDTO)
        {
            Exercise exercise = new Exercise(exerciseDTO.ExerciseID, exerciseDTO.Name, exerciseDTO.UserID, (ExerciseType)exerciseDTO.ExerciseType);
            return exercise;
        }

        private ExerciseViewModel ConvertExerciseDTOToVM(ExerciseDTO exerciseDTO)
        {
            ExerciseViewModel exerciseViewModel = new ExerciseViewModel
            {
                ExerciseType = (ExerciseType)exerciseDTO.ExerciseType,
                Name = exerciseDTO.Name,
                UserID = exerciseDTO.UserID
            };
            return exerciseViewModel;
        }

        private User ConvertUserDTO(UserDTO userDTO)
        {
            User user = new User(userDTO.Name, userDTO.UserID, userDTO.Password, ConvertTrainingDTOs(userDTO.GetTrainings()), ConvertExerciseDTOs(userDTO.GetExercises()));

            return user;
        }

        private List<Training> ConvertTrainingDTOs(List<TrainingDTO> trainingDTOs)
        {
            List<Training> trainings = new List<Training>();
            foreach (var trainingDTO in trainingDTOs)
            {
                Training training = new Training(trainingDTO.TrainingID, trainingDTO.UserID, trainingDTO.Date, (TrainingType)trainingDTO.TrainingType);
                trainings.Add(training);
            }
            return trainings;
        }

        private TrainingViewModel ConvertTrainingDTO(TrainingDTO trainingDTO)
        {
            TrainingViewModel training = new TrainingViewModel
            {
                Date = trainingDTO.Date,
                TrainingID = trainingDTO.TrainingID,
                TrainingType = (TrainingType)trainingDTO.TrainingType
            };
            return training;
        }

        private List<Exercise> ConvertExerciseDTOs(List<ExerciseDTO> exerciseDTOs)
        {
            List<Exercise> exercises = new List<Exercise>();
            if (exerciseDTOs != null)
            {
                foreach (var exerciseDTO in exerciseDTOs)
                {
                    Exercise exercise = new Exercise(exerciseDTO.ExerciseID, exerciseDTO.Name, exerciseDTO.UserID, (ExerciseType)exerciseDTO.ExerciseType);
                    exercises.Add(exercise);
                }
            }

            return exercises;
        }

        private SetViewModel ConvertSetDTO(SetDTO setDTO)
        {
            SetViewModel setViewModel = new SetViewModel
            {
                RoundID = setDTO.RoundID,
                SetID = setDTO.SetID,
                SetOrder = setDTO.SetOrder,
                Weight = setDTO.Weight
            };
            return setViewModel;
        }
    }
}

Fitness Applicatie/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FitTracker</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">FitTracker</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Training" asp-action="AddStrengthTraining">Add Strength Training</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Training" asp-action="AddCardioTraining">Add Cardio Training</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Exercise" asp-action="AddStrengthExercise"> Add Exercise</a>
                        </li>
                    </ul>
                </div>
                <div class="login-container ml-auto d-inline-flex">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - FitTracker - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>