Fitness Applicatie/Models/ExerciseViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace Fitness_Applicatie.Models
{
    public class ExerciseViewModel
    {
        public string Name { get; set; }
        public Guid UserID { get; set; }
        public ExerciseType ExerciseType { get; set; }
    }
}

Fitness Applicatie/Controllers/ExerciseController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using FitTracker.Logic;
using FitTracker.Interface.DTOs;
using Microsoft.AspNetCore.Mvc;

namespace Fitness_Applicatie.Controllers
{
    public class ExerciseController : Controller
    {
        [Authorize]
        public IActionResult AddStrengthExercise()
        {
            return View();
        }

        public ActionResult AddExerciseToDb(Models.ExerciseViewModel exercise)
        {
            return LocalRedirect("/Home/Index");
        }

        [HttpPost]
        public IActionResult AddStrengthExercise(Models.ExerciseViewModel exerciseViewModel)
        {
            try
            {
                User user = new User();
                Exercise exercise = new Exercise();
                ExerciseDTO exerciseDTO = new ExerciseDTO(exerciseViewModel.Name, Guid.Parse(User.FindFirst("Id").Value), (ExerciseTypeDTO)exerciseViewModel.ExerciseType);
                if (String.IsNullOrEmpty(exerciseViewModel.Name) || exerciseViewModel.ExerciseType.ToString() == "Empty")
                {
                    ModelState.AddModelError("Name", "Fill in all fields please");
                    return View(exerciseViewModel);
                }
                if (exercise.ExerciseExists(exerciseViewModel.Name))
                {
                    ModelState.AddModelError("Name", "Exercise already exists");
                    return View(exerciseViewModel);
                }
                else
                {
                    user.AddExercise(exerciseDTO);
                    TempData["JustAddedExercise"] = true;
                }
                return LocalRedirect("/Home/Index");
            }
            catch
            {
                TempData["Error"] = true;
                return LocalRedirect("/Home/Index");
            }
        }
    }
}

Fitness Applicatie/Views/Exercise/AddStrengthExercise.cshtml
@model Fitness_Applicatie.Models.ExerciseViewModel

@{
    ViewData["Title"] = "Add Exercise";
}

<div class="row">
    <div class="col-4">

    </div>

    <div class="col-4">
        @using (Html.BeginForm("AddStrengthExercise", "Exercise", FormMethod.Post, new { enctype = "multipart/form-data", onsubmit = "setContent()" }))
        {
            <div class="form-group text-center">
                <label asp-for="Name"></label>
                <input asp-for="Name" />
            </div>
            <br />
            <div class="form-group text-center">
                <label asp-for="ExerciseType">What kind of exercise is it?</label>
                <br />
                <input type="radio" name="exerciseType" asp-for="ExerciseType" value="Bodyweight" />Bodyweight
                <input type="radio" name="exerciseType" asp-for="ExerciseType" value="Weighted" />Weighted
                <input type="radio" name="exerciseType" asp-for="ExerciseType" value="Cardio" />Cardio
            </div>
            <div class="form-group text-center">
                <input type="submit" value="Add" />
            </div>
            <div class="text-danger text-center">
                @Html.ValidationMessageFor(vm => vm.Name)
            </div>
        }
    </div>

    <div class="col-4">

    </div>
</div>